extends RefCounted
## Generated from supplied VRM humanoid metadata.

const PAIRS := [
	["pelvis", "root"],
	["spine_01", "DEF-Spine"],
	["spine_02", "DEF-Chest"],
	["spine_03", "DEF-Upper Chest"],
	["neck_01", "DEF-Neck"],
	["Head", "DEF-Head"],
	["upperarm_l", "DEF-Left arm"],
	["lowerarm_l", "DEF-Left elbow"],
	["hand_l", "DEF-Left wrist"],
	["thigh_l", "DEF-Left leg"],
	["calf_l", "DEF-Left knee"],
	["foot_l", "DEF-Left ankle"],
	["ball_l", "DEF-Left toe"],
	["thumb_01_l", "DEF-Thumb0_L"],
	["thumb_02_l", "DEF-Thumb1_L"],
	["thumb_03_l", "DEF-Thumb2_L"],
	["index_01_l", "DEF-IndexFinger1_L"],
	["index_02_l", "DEF-IndexFinger2_L"],
	["index_03_l", "DEF-IndexFinger3_L"],
	["middle_01_l", "DEF-MiddleFinger1_L"],
	["middle_02_l", "DEF-MiddleFinger2_L"],
	["middle_03_l", "DEF-MiddleFinger3_L"],
	["ring_01_l", "DEF-RingFinger1_L"],
	["ring_02_l", "DEF-RingFinger2_L"],
	["ring_03_l", "DEF-RingFinger3_L"],
	["pinky_01_l", "DEF-LittleFinger1_L"],
	["pinky_02_l", "DEF-LittleFinger2_L"],
	["pinky_03_l", "DEF-LittleFinger3_L"],
	["upperarm_r", "DEF-Right arm"],
	["lowerarm_r", "DEF-Right elbow"],
	["hand_r", "DEF-Right wrist"],
	["thigh_r", "DEF-Right leg"],
	["calf_r", "DEF-Right knee"],
	["foot_r", "DEF-Right ankle"],
	["ball_r", "DEF-Right toe"],
	["thumb_01_r", "DEF-Thumb0_R"],
	["thumb_02_r", "DEF-Thumb1_R"],
	["thumb_03_r", "DEF-Thumb2_R"],
	["index_01_r", "DEF-IndexFinger1_R"],
	["index_02_r", "DEF-IndexFinger2_R"],
	["index_03_r", "DEF-IndexFinger3_R"],
	["middle_01_r", "DEF-MiddleFinger1_R"],
	["middle_02_r", "DEF-MiddleFinger2_R"],
	["middle_03_r", "DEF-MiddleFinger3_R"],
	["ring_01_r", "DEF-RingFinger1_R"],
	["ring_02_r", "DEF-RingFinger2_R"],
	["ring_03_r", "DEF-RingFinger3_R"],
	["pinky_01_r", "DEF-LittleFinger1_R"],
	["pinky_02_r", "DEF-LittleFinger2_R"],
	["pinky_03_r", "DEF-LittleFinger3_R"],
]
